# Generated by Django 5.0.4 on 2024-06-08 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shoe_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeMetadata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(default='Brand', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField()),
                ('classification', models.CharField(default='Unknown', max_length=30)),
                ('classification_confidence', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeDominantColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_percentage', models.FloatField()),
                ('red', models.IntegerField()),
                ('green', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('shoe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoeimage')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boots_confidence', models.FloatField()),
                ('flip_flops_confidence', models.FloatField()),
                ('loafers_confidence', models.FloatField()),
                ('sandals_confidence', models.FloatField()),
                ('sneakers_confidence', models.FloatField()),
                ('soccer_shoes_confidence', models.FloatField()),
                ('shoe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoeimage')),
            ],
        ),
        migrations.AddField(
            model_name='shoeimage',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='evaluate.shoemetadata'),
        ),
        migrations.CreateModel(
            name='ShoeProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_red', models.FloatField()),
                ('percentage_green', models.FloatField()),
                ('percentage_blue', models.FloatField()),
                ('shoe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoeimage')),
            ],
        ),
    ]
