# Generated by Django 5.0.4 on 2024-06-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeHistograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_histogram', models.BinaryField()),
                ('green_histogram', models.BinaryField()),
                ('blue_histogram', models.BinaryField()),
                ('shoe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoeimage')),
            ],
        ),
    ]
