# Generated by Django 5.0.4 on 2024-05-30 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_remove_shoemetadata_images_shoeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_red', models.FloatField()),
                ('percentage_green', models.FloatField()),
                ('percentage_blue', models.FloatField()),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoemetadata')),
            ],
        ),
    ]
