# Generated by Django 5.0.4 on 2024-06-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_shoehistograms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoeHOG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hog_descriptor', models.BinaryField()),
                ('shoe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoeimage')),
            ],
        ),
        migrations.CreateModel(
            name='ShoeLBP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbp_histogram', models.BinaryField()),
                ('shoe_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoeimage')),
            ],
        ),
    ]
