# Generated by Django 5.0.4 on 2024-06-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0003_shoehog_shoelbp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoeimage',
            name='image',
            field=models.BinaryField(),
        ),
    ]
