# Generated by Django 5.0.4 on 2024-06-03 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0004_shoemetadata_brand_alter_shoeimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoemetadata',
            name='brand',
            field=models.CharField(default='Brand', max_length=30),
        ),
        migrations.CreateModel(
            name='ShoeDominantColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_percentage', models.FloatField()),
                ('red', models.IntegerField()),
                ('green', models.IntegerField()),
                ('blue', models.IntegerField()),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoemetadata')),
            ],
        ),
    ]
