# Generated by Django 5.0.4 on 2024-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0004_alter_shoeimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoehog',
            name='hog_columns',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoehog',
            name='hog_rows',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoelbp',
            name='lbp_columns',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoelbp',
            name='lbp_rows',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
