# Generated by Django 5.0.4 on 2024-06-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0005_shoehog_hog_columns_shoehog_hog_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoeimage',
            name='image_local',
            field=models.ImageField(default=1, upload_to='shoe_images/'),
            preserve_default=False,
        ),
    ]
