# Generated by Django 5.0.4 on 2024-06-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0006_shoeimage_image_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoemetadata',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shoemetadata',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
