# Generated by Django 5.0.4 on 2024-06-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0007_alter_shoemetadata_name_alter_shoemetadata_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
