# Generated by Django 5.0.4 on 2024-06-23 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0008_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoemetadata',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluate.website'),
        ),
    ]
