# Generated by Django 5.0.4 on 2024-06-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0009_shoemetadata_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='logo',
            field=models.BinaryField(default=b'')
        ),
    ]
