# Generated by Django 5.0.4 on 2024-05-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoemetadata',
            name='images',
        ),
        migrations.CreateModel(
            name='ShoeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoemetadata')),
            ],
        ),
    ]
