# Generated by Django 5.0.4 on 2024-06-01 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0003_shoeproperties'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoemetadata',
            name='brand',
            field=models.CharField(default='Brand', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoeimage',
            name='image',
            field=models.ImageField(upload_to='shoe_images/'),
        ),
        migrations.AlterField(
            model_name='shoeimage',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='evaluate.shoemetadata'),
        ),
        migrations.AlterField(
            model_name='shoemetadata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
