# Generated by Django 5.0.4 on 2024-06-03 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0005_alter_shoemetadata_brand_shoedominantcolor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoedominantcolor',
            name='shoe',
        ),
        migrations.RemoveField(
            model_name='shoeproperties',
            name='shoe',
        ),
        migrations.AddField(
            model_name='shoedominantcolor',
            name='shoe_image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoeimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoeproperties',
            name='shoe_image',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='evaluate.shoeimage'),
            preserve_default=False,
        ),
    ]
