# Generated by Django 5.0.4 on 2024-06-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0007_remove_shoemetadata_url_shoemetadata_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoemetadata',
            name='classification_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shoemetadata',
            name='url',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
    ]
